# Generated by Django 4.2.27 on 2025-12-03 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("RUB", "Russian Ruble"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("recipient_details", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payouts_payout",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="payouts_pay_status_a5ad2e_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="payouts_pay_created_b65d12_idx"
                    ),
                ],
            },
        ),
    ]
